### ISSUE TITLE
Exception when checking for updates while window is minimized: System.NullReferenceException

### ISSUE THREAD

**Issue by marth8880** [marth8880/ZeroMunge#10]
Repro:

1. Launch application.
2. Continually click in an Explorer window (or elsewhere) to ensure that the application window is instantiated in a minimized state.

```
System.NullReferenceException
  HResult=0x80004003
  Message=Object reference not set to an instance of an object.
  Source=ZeroMunge
  StackTrace:
   at ZeroMunge.Utilities.<CheckForInternetConnection>g__TryConnection|21_0(String url) in C:\Users\aaron\source\repos\ZeroMunge\ZeroMunge\Modules\Utilities.cs:line 837
   at ZeroMunge.Utilities.CheckForInternetConnection() in C:\Users\aaron\source\repos\ZeroMunge\ZeroMunge\Modules\Utilities.cs:line 863
   at ZeroMunge.Utilities.CheckForUpdates() in C:\Users\aaron\source\repos\ZeroMunge\ZeroMunge\Modules\Utilities.cs:line 761
   at ZeroMunge.ZeroMunge.ZeroMunge_Shown(Object sender, EventArgs e) in C:\Users\aaron\source\repos\ZeroMunge\ZeroMunge\Forms\Main.cs:line 142
   at System.Windows.Forms.Form.OnShown(EventArgs e)
   at System.Windows.Forms.Control.InvokeMarshaledCallbackHelper(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Forms.Control.InvokeMarshaledCallback(ThreadMethodEntry tme)
   at System.Windows.Forms.Control.InvokeMarshaledCallbacks()
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.Form.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.DebuggableCallback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
   at System.Windows.Forms.UnsafeNativeMethods.DispatchMessageW(MSG& msg)
   at System.Windows.Forms.Application.ComponentManager.System.Windows.Forms.UnsafeNativeMethods.IMsoComponentManager.FPushMessageLoop(IntPtr dwComponentID, Int32 reason, Int32 pvLoopData)
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoopInner(Int32 reason, ApplicationContext context)
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoop(Int32 reason, ApplicationContext context)
   at ZeroMunge.Program.Main() in C:\Users\aaron\source\repos\ZeroMunge\ZeroMunge\Program.cs:line 19
```

**Comment by marth8880** [comment]
Issue fixed in 8ff8c94 - closing.
