### ISSUE TITLE
Exception when loading save file that contains empty file list: NullReferenceException

### ISSUE THREAD

**Issue by marth8880** [marth8880/ZeroMunge#22]
```
System.NullReferenceException
  HResult=0x80004003
  Message=Object reference not set to an instance of an object.
  Source=ZeroMunge
  StackTrace:
   at ZeroMunge.ZeroMunge.LoadDataIntoFileList(DataFilesContainer data, Boolean replaceCurrentContents) in C:\Users\Aaron\Source\Repos\ZeroMunge\ZeroMunge\Forms\Main.cs:line 1741
   at ZeroMunge.ZeroMunge.openDlg_OpenFileListPrompt_FileOk(Object sender, CancelEventArgs e) in C:\Users\Aaron\Source\Repos\ZeroMunge\ZeroMunge\Forms\Main.cs:line 3100
   at System.Windows.Forms.FileDialog.OnFileOk(CancelEventArgs e)
   at System.Windows.Forms.FileDialog.HandleVistaFileOk(IFileDialog dialog)
   at System.Windows.Forms.FileDialog.VistaDialogEvents.OnFileOk(IFileDialog pfd)
```

**Comment by marth8880** [comment]
Issue fixed in fd67d0d - closing.
