### ISSUE TITLE
Exception when attempting to commit empty Munged Files list: System.IndexOutOfRangeException

### ISSUE THREAD

**Issue by marth8880** [marth8880/ZeroMunge#5]
```
System.IndexOutOfRangeException
  HResult=0x80131508
  Message=Index was outside the bounds of the array.
  Source=ZeroMunge
  StackTrace:
   at ZeroMunge.ZeroMunge.text_MungedFilesEdit_Commit() in C:\Users\aaron\source\repos\ZeroMunge\ZeroMunge\Forms\Main.cs:line 2179
   at ZeroMunge.ZeroMunge.text_MungedFilesEdit_KeyDown(Object sender, KeyEventArgs e) in C:\Users\aaron\source\repos\ZeroMunge\ZeroMunge\Forms\Main.cs:line 2105
   at System.Windows.Forms.Control.OnKeyDown(KeyEventArgs e)
   at System.Windows.Forms.Control.ProcessKeyEventArgs(Message& m)
   at System.Windows.Forms.Control.WmKeyChar(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.RichTextBox.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.DebuggableCallback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
   at System.Windows.Forms.UnsafeNativeMethods.DispatchMessageW(MSG& msg)
   at System.Windows.Forms.Application.ComponentManager.System.Windows.Forms.UnsafeNativeMethods.IMsoComponentManager.FPushMessageLoop(IntPtr dwComponentID, Int32 reason, Int32 pvLoopData)
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoopInner(Int32 reason, ApplicationContext context)
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoop(Int32 reason, ApplicationContext context)
   at ZeroMunge.Program.Main() in C:\Users\aaron\source\repos\ZeroMunge\ZeroMunge\Program.cs:line 19
```

**Comment by marth8880** [comment]
Issue fixed in db07bcf - closing.
