### ISSUE TITLE
Exception when job finishes that contains an empty Munged Files list: System.ArgumentOutOfRangeException

### ISSUE THREAD

**Issue by marth8880** [marth8880/ZeroMunge#6]
```
System.ArgumentOutOfRangeException
  HResult=0x80131502
  Message=Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index
  Source=mscorlib
  StackTrace:
   at System.ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument argument, ExceptionResource resource)
   at System.Collections.Generic.List`1.get_Item(Int32 index)
   at ZeroMunge.ZeroMunge.ProcManager_NotifyProcessComplete(Int32 whichFile, Boolean singleFile) in C:\Users\aaron\source\repos\ZeroMunge\ZeroMunge\Forms\Main.cs:line 423
   at ZeroMunge.ZeroMunge.<>c__DisplayClass52_0.<ProcManager_StartProcess>b__2(Object sender, EventArgs e) in C:\Users\aaron\source\repos\ZeroMunge\ZeroMunge\Forms\Main.cs:line 625
   at System.Diagnostics.Process.OnExited()
   at System.Diagnostics.Process.RaiseOnExited()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading._ThreadPoolWaitOrTimerCallback.PerformWaitOrTimerCallback(Object state, Boolean timedOut)
```

**Comment by marth8880** [comment]
Issue fixed in 5d46eb8 - closing.
